tap 'codeclimate/formulae'
tap 'dbcli/tap'

cask 'chromedriver'
cask 'java'
cask 'homebrew/cask-versions/java8'

brew 'autojump'
brew 'awscli'
brew 'bat'
brew 'cabal-install'
brew 'codeclimate'
brew 'curl', args: ['with-nghttp2']
brew 'diff-so-fancy'
brew 'elasticsearch'
brew 'elixir'
brew 'exercism'
brew 'git'
brew 'git-flow'
brew 'git-lfs'
brew 'go'
brew 'gradle'
brew 'haskell-stack'
brew 'hub'
brew 'hugo'
brew 'httpie'
brew 'jq'
brew 'kibana'
brew 'libshout'
brew 'logstash'
brew 'mosh'
brew 'neovim'
brew 'openssl'
brew 'overmind'
brew 'postgresql'
brew 'pgcli'
brew 'python'
brew 'redis'
brew 'vim'
brew 'wget'
brew 'yarn', args: ['without-node']
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-completions'

# For akatosh dev
tap 'bbc/audiowaveform'
brew 'audiowaveform'
brew 'taglib'
