brew 'awscli'
brew 'cabal-install'
brew 'codeclimate'
brew 'curl', args: ['with-nghttp2']
brew 'diff-so-fancy'
brew 'elasticsearch'
brew 'elixir'
brew 'exercism'
brew 'forego'
brew 'git'
brew 'git-flow'
brew 'git-lfs'
brew 'go'
brew 'kibana'
brew 'logstash'
brew 'openssl'
brew 'phantomjs'
brew 'postgresql'
brew 'redis'
brew 'rust'
brew 'watchman'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'
# brew 'zsh-completions'

# For akatosh dev
brew 'taglib'
